---
- name: Install build depends
  include_tasks: "build_depends_{{ ansible_pkg_mgr }}.yaml"

- name: Download emacs
  shell: |
    curl -L http://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-{{ emacs_version }}.tar.gz |
    tar -xzf -
  args:
    chdir: "{{ work_dir }}"
    creates: "emacs-{{ emacs_version }}"

- name: Build emacs
  shell: |
    ./configure --prefix {{ install_prefix }} {{ build_options }}
    make
  args:
    chdir: "{{ work_dir }}/emacs-{{ emacs_version }}"
    creates: "src/emacs"

- name: Install emacs
  shell: |
    make install
  become: yes
  args:
    chdir: "{{ work_dir }}/emacs-{{ emacs_version }}"
    creates: "{{ install_prefix }}/bin/emacs"
